//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeShareClient2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserModel", Namespace="http://schemas.datacontract.org/2004/07/WeShare")]
    [System.SerializableAttribute()]
    public partial class UserModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AllergiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Allergies {
            get {
                return this.AllergiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AllergiesField, value) != true)) {
                    this.AllergiesField = value;
                    this.RaisePropertyChanged("Allergies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPR {
            get {
                return this.CPRField;
            }
            set {
                if ((object.ReferenceEquals(this.CPRField, value) != true)) {
                    this.CPRField = value;
                    this.RaisePropertyChanged("CPR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuidLine {
            get {
                return this.GuidLineField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidLineField, value) != true)) {
                    this.GuidLineField = value;
                    this.RaisePropertyChanged("GuidLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodModel", Namespace="http://schemas.datacontract.org/2004/07/WeShare")]
    [System.SerializableAttribute()]
    public partial class FoodModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AllergiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Allergies {
            get {
                return this.AllergiesField;
            }
            set {
                if ((object.ReferenceEquals(this.AllergiesField, value) != true)) {
                    this.AllergiesField = value;
                    this.RaisePropertyChanged("Allergies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpDate {
            get {
                return this.ExpDateField;
            }
            set {
                if ((this.ExpDateField.Equals(value) != true)) {
                    this.ExpDateField = value;
                    this.RaisePropertyChanged("ExpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuidLine {
            get {
                return this.GuidLineField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidLineField, value) != true)) {
                    this.GuidLineField = value;
                    this.RaisePropertyChanged("GuidLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoPath {
            get {
                return this.PhotoPathField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoPathField, value) != true)) {
                    this.PhotoPathField = value;
                    this.RaisePropertyChanged("PhotoPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWeShareService")]
    public interface IWeShareService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetAllUsers", ReplyAction="http://tempuri.org/IWeShareService/GetAllUsersResponse")]
        WeShareClient2.ServiceReference1.UserModel[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetAllUsers", ReplyAction="http://tempuri.org/IWeShareService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetUserByCPR", ReplyAction="http://tempuri.org/IWeShareService/GetUserByCPRResponse")]
        WeShareClient2.ServiceReference1.UserModel GetUserByCPR(string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetUserByCPR", ReplyAction="http://tempuri.org/IWeShareService/GetUserByCPRResponse")]
        System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel> GetUserByCPRAsync(string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetUserByEmail", ReplyAction="http://tempuri.org/IWeShareService/GetUserByEmailResponse")]
        WeShareClient2.ServiceReference1.UserModel GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetUserByEmail", ReplyAction="http://tempuri.org/IWeShareService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/AddUser", ReplyAction="http://tempuri.org/IWeShareService/AddUserResponse")]
        int AddUser(WeShareClient2.ServiceReference1.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/AddUser", ReplyAction="http://tempuri.org/IWeShareService/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(WeShareClient2.ServiceReference1.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/DeleteUser", ReplyAction="http://tempuri.org/IWeShareService/DeleteUserResponse")]
        int DeleteUser(WeShareClient2.ServiceReference1.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/DeleteUser", ReplyAction="http://tempuri.org/IWeShareService/DeleteUserResponse")]
        System.Threading.Tasks.Task<int> DeleteUserAsync(WeShareClient2.ServiceReference1.UserModel user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/AddFood", ReplyAction="http://tempuri.org/IWeShareService/AddFoodResponse")]
        int AddFood(WeShareClient2.ServiceReference1.FoodModel food, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/AddFood", ReplyAction="http://tempuri.org/IWeShareService/AddFoodResponse")]
        System.Threading.Tasks.Task<int> AddFoodAsync(WeShareClient2.ServiceReference1.FoodModel food, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/TakeFood", ReplyAction="http://tempuri.org/IWeShareService/TakeFoodResponse")]
        int TakeFood(WeShareClient2.ServiceReference1.FoodModel food, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/TakeFood", ReplyAction="http://tempuri.org/IWeShareService/TakeFoodResponse")]
        System.Threading.Tasks.Task<int> TakeFoodAsync(WeShareClient2.ServiceReference1.FoodModel food, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetAllAllergies", ReplyAction="http://tempuri.org/IWeShareService/GetAllAllergiesResponse")]
        string[] GetAllAllergies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetAllAllergies", ReplyAction="http://tempuri.org/IWeShareService/GetAllAllergiesResponse")]
        System.Threading.Tasks.Task<string[]> GetAllAllergiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetPasswordKey", ReplyAction="http://tempuri.org/IWeShareService/GetPasswordKeyResponse")]
        string[] GetPasswordKey(string cpr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWeShareService/GetPasswordKey", ReplyAction="http://tempuri.org/IWeShareService/GetPasswordKeyResponse")]
        System.Threading.Tasks.Task<string[]> GetPasswordKeyAsync(string cpr);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWeShareServiceChannel : WeShareClient2.ServiceReference1.IWeShareService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeShareServiceClient : System.ServiceModel.ClientBase<WeShareClient2.ServiceReference1.IWeShareService>, WeShareClient2.ServiceReference1.IWeShareService {
        
        public WeShareServiceClient() {
        }
        
        public WeShareServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeShareServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeShareServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeShareServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WeShareClient2.ServiceReference1.UserModel[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WeShareClient2.ServiceReference1.UserModel GetUserByCPR(string cpr) {
            return base.Channel.GetUserByCPR(cpr);
        }
        
        public System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel> GetUserByCPRAsync(string cpr) {
            return base.Channel.GetUserByCPRAsync(cpr);
        }
        
        public WeShareClient2.ServiceReference1.UserModel GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<WeShareClient2.ServiceReference1.UserModel> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public int AddUser(WeShareClient2.ServiceReference1.UserModel user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(WeShareClient2.ServiceReference1.UserModel user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public int DeleteUser(WeShareClient2.ServiceReference1.UserModel user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserAsync(WeShareClient2.ServiceReference1.UserModel user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public int AddFood(WeShareClient2.ServiceReference1.FoodModel food, string email) {
            return base.Channel.AddFood(food, email);
        }
        
        public System.Threading.Tasks.Task<int> AddFoodAsync(WeShareClient2.ServiceReference1.FoodModel food, string email) {
            return base.Channel.AddFoodAsync(food, email);
        }
        
        public int TakeFood(WeShareClient2.ServiceReference1.FoodModel food, string email) {
            return base.Channel.TakeFood(food, email);
        }
        
        public System.Threading.Tasks.Task<int> TakeFoodAsync(WeShareClient2.ServiceReference1.FoodModel food, string email) {
            return base.Channel.TakeFoodAsync(food, email);
        }
        
        public string[] GetAllAllergies() {
            return base.Channel.GetAllAllergies();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllAllergiesAsync() {
            return base.Channel.GetAllAllergiesAsync();
        }
        
        public string[] GetPasswordKey(string cpr) {
            return base.Channel.GetPasswordKey(cpr);
        }
        
        public System.Threading.Tasks.Task<string[]> GetPasswordKeyAsync(string cpr) {
            return base.Channel.GetPasswordKeyAsync(cpr);
        }
    }
}
